# Site Settings
title: Econ 103 - Statistics for Economists 
author: Francis J. DiTraglia
email: fditra@sas.upenn.edu
description: Course website for Econ 103 for UPenn

# Build Settings
theme: minima
markdown: kramdown
